services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_BACKEND_URL=http://localhost:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge